
trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- checkout: self

- task: TerraformInstaller@1
  inputs:
    terraformVersion: '1.6.6'

- task: TerraformTaskV4@4
  inputs:
    provider: 'azurerm'
    command: 'init'
    workingDirectory: '$(System.DefaultWorkingDirectory)'
    backendServiceArm: 'aksdemo1'
    backendAzureRmResourceGroupName: 'tfstate-rg'
    backendAzureRmStorageAccountName: 'aksdemostorage004'
    backendAzureRmContainerName: 'aksdemotfstate'
    backendAzureRmKey: 'aks.tfstate'

- task: TerraformTaskV4@4
  inputs:
    provider: 'azurerm'
    command: 'plan'
    workingDirectory: '$(System.DefaultWorkingDirectory)'
    environmentServiceNameAzureRM: 'aksdemo1'
    allowTelemetryCollection: false

   # Copy terraform folder to staging directory
- task: CopyFiles@2
  inputs:
    SourceFolder: '$(System.DefaultWorkingDirectory)/aksmydemocode'
    Contents: '**'
    TargetFolder: '$(Build.ArtifactStagingDirectory)/aksmydemocode'

# Publish staging folder as artifact
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)/terraform'
    ArtifactName: 'drop'
    publishLocation: 'Container'

- task: TerraformTaskV4@4
  inputs:
    provider: 'azurerm'
    command: 'apply'
    workingDirectory: '$(System.DefaultWorkingDirectory)'
    environmentServiceNameAzureRM: 'aksdemo1'
    allowTelemetryCollection: false
    args: '-auto-approve'
